apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: yourdomain-com-tls
spec:
  secretName: yourdomain-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: yourdomain-com-tls
  dnsNames:
    - yourdomain.com
    - www.yourdomain.com
    acme:
      config:
        - http01:
            ingressClass: nginx
          domains:
            - yourdomain.com
            - www.yourdomain.com